### PR TITLE
Update to 1.20.1

### PR DESCRIPTION
**Pull request by maityyy**
I tried not to change the original code as much as possible and just update to the new version. 1.20.2 and 1.20.3 should not work, Mojang have been making a lot more changes in minor versions recently. I also recommend to filter json files

### CODE REVIEW

**Comment by maityyy** [comment]
I also removed `@Enviroment(Env.CLIENT)` as this is not intended for modders, these annotations are only needed for the game sources. It was giving me errors for some reason

**Review by dhyces — APPROVED** [review]

**Comment by dhyces** [comment]
Hey, thanks for all of your hard work! One question, how do you suggest we filter json files?

**Comment by maityyy** [comment]
I meant this
image

**Comment by dhyces** [comment]
Ah, gotcha, thought you meant the pack mcmeta filter 😄

**Pull request merged**
